name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      - name: Configure custom domain
        run: echo "carlosymaria.es" > dist/CNAME
        
      - name: Add mime.types file for proper MIME types
        run: |
          cat > dist/.htaccess << 'EOL'
          AddType application/javascript .js
          AddType application/javascript .mjs
          AddType text/javascript .js
          AddType text/javascript .mjs
          EOL

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        id: deployment
        with:
          folder: dist
          branch: gh-pages
          clean: true
