name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      - name: Configure custom domain
        run: echo "carlosymaria.es" > dist/CNAME
        
      - name: Add files for proper GitHub Pages configuration
        run: |
          # Create .nojekyll to disable Jekyll processing
          touch dist/.nojekyll
          
          # Create a simple static HTML file to test that everything works
          cat > dist/test-static.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Static Test Page</title>
            <style>
              body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
              h1 { color: #333; }
              .success { color: green; font-weight: bold; }
            </style>
          </head>
          <body>
            <h1>María & Carlos Wedding Website</h1>
            <p>This is a static test page to verify that the website is working correctly.</p>
            <p class="success">If you can see this page, the deployment is successful!</p>
            <script>
              document.write('<p>JavaScript is working correctly!</p>');
            </script>
            <p><a href="/">Go to the main website</a></p>
          </body>
          </html>
          EOL

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        id: deployment
        with:
          folder: dist
          branch: gh-pages
          clean: true
